### ISSUE TITLE
Back Camera

### ISSUE THREAD

**Issue by guidouil** [hitchcott/meteor-qr-code-scanner#1]
Hi, I was wondering if you could include a back camera selector for smartphones, this would be much more efficient to scan a QRcode I think.
There is a demo here where you can select the second camera with getUserMedia https://simpl.info/getusermedia/sources/

Thanks for your time and package :+1:

**Comment by IstoraMandiri** [comment]
Thanks for the feedback @guidouil 

Definitely something I agree should be implemented. I'll get around to implementing it shortly.

In the meantime, check out @fix 's branch, https://github.com/fix/meteor-qr-code-scanner/commit/f78f3fefba2e25931aa9ec1aaa99d3fe102c615d

I will probably implement something very similar to this, and I'm happy to take the PR if he see's this!

**Comment by fix** [comment]
Hi, well this fix is not working yet, i discovered it was slightly more complicated than i thought. Above all due to the UX (firefox proposes which camera you want to use, not chrome, etc...)
I'll work on it this week, since I 'll have some spare time.

**Comment by guidouil** [comment]
Merci François-Xavier :)

2014-11-05 8:45 GMT+01:00 François-Xavier Thoorens <notifications@github.com

> :
> 
> Hi, well this fix is not working yet, i discovered it was slightly more
> complicated than i thought. Above all due to the UX (firefox proposes which
> camera you want to use, not chrome, etc...)
> I'll work on it this week, since I 'll have some spare time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hitchcott/meteor-qr-code-scanner/issues/1#issuecomment-61770590
> .

## 

Guillaume Darbonne
Mob : +33 6 32 42 48 49
Skype : guidouil

**Comment by freaker2k7** [comment]
I have a working code for that :)

I need permission to create a new branch so I can do a pull request :)

**Comment by IstoraMandiri** [comment]
Hi @freaker2k7  -- feel free to fork and make a pull request! :+1:

**Comment by freaker2k7** [comment]
Hi :)

Already did ^_^

Please check it as well. (works now fine for me)

A bit later, I'll do the back camera fix :D

Thanks for the ability to assist ^_^

## 

B NICE... JUST B !

**Comment by rohanray** [comment]
Hi, I am trying to use this on Chrome mobile browser on Android 5.0, however, I still don't get an option to select the rear camera. Looking for some help on this.

Regards
Rohan

**Comment by IstoraMandiri** [comment]
Hi @rohanray the current implementation will automatically select the back camera if it exists, and falls back to front facing camera if it cannot find a back camera.

**Comment by rohanray** [comment]
Hi @hitchcott thanks for the response!

Unfortunately, that does not seem to be the case with me. I have tested it on two Asus zenfones (android 5.0) using Chrome mobile browser, it just always uses the front facing camera.

Am I doing something wrong? Please can you assist me?

Thanks
Ray

**Comment by rohanray** [comment]
Hi @hitchcott, the issue got fixed after changing the package from "mrt:qr-scanner" to "hitchcott:qr-scanner". It's really confusing as the github links for both the projects on atmosphere points to this repository. However, they don't behave the same.

**Comment by guidouil** [comment]
@rohanray flag the mrt version :smile:

**Comment by rohanray** [comment]
Let's wait to hear from @hitchcott

**Comment by IstoraMandiri** [comment]
The the `mrt` version can be ignored/flagged! It was for meteor <=  0.8.3. those were the days

**Comment by rohanray** [comment]
ok. thanks for the info!

**Comment by tophsic** [comment]
I did not manage to select rear camera on Chrome 56 with Meteor 1.4. So I forked and made this commit https://github.com/mapstime/meteor-qr-code-scanner/commit/904c818295c04ba3ff4201a90c252f5d23c388a6.
