### ISSUE TITLE
qrScanner not working in Meteor 1.2.1 with crosswalk?

### ISSUE THREAD

**Issue by ericvrp** [hitchcott/meteor-qr-code-scanner#12]
I20151112-16:45:55.417(1) (android:http://meteor.local/packages/hitchcott_qr-scanner.js:4301) Uncaught TypeError: Cannot read property 'kind' of undefined

Is the error I get from a basic test after.

meteor add test
cd test
adding: {{> qrScanner}} to test.html
meteor add-platform android
meteor add crosswalk
meteor add hitchcott:qr-scanner
meteor run android-device

**Comment by IstoraMandiri** [comment]
My guess is that Cordova doesn't support the web api for `getUserMedia`, meaning we'd have to use something like https://github.com/apache/cordova-plugin-camera - preferably seamlessly using `if Meteor.isCordvoa`.

Closing for now, moving to issue #14 (let me know if this is incorrect and I can re-open this).
