### ISSUE TITLE
Is there a way to switch off cleanly the camera

### ISSUE THREAD

**Issue by fix** [hitchcott/meteor-qr-code-scanner#2]
Hi,
I could not find a hook to switch of the camera. My use case is a toogle button to switch on/of the camera.

The code is the following. `browserIsCompatible` is a function to check if getUserMedia exists. The button switches on/off a value that is then output to `qrCodeActivated`

```
  {{#if browserIsCompatible}}
    <button id="qrActivator" class="btn btn-info fa fa-qrcode"> QRScanner</button>
    {{#if qrCodeActivated}}
      {{> qrScanner}}
    {{/if}}
  {{/if}}
```

**Comment by freaker2k7** [comment]
I just extended the package and I want to do a pull request :)
