### ISSUE TITLE
Can't access camera on iOS/Chrome/Safari

### ISSUE THREAD

**Issue by drone1** [hitchcott/meteor-qr-code-scanner#21]
I have a simple test up locally that doesn't work at all. It shows a circular play button to start the 'video', and touching that button does nothing. No errors in console or warnings, etc. The hover state of the button activates so I know I'm pushing it. I wonder if the world of spam on phones ruined things for the rest of us here. 

I also noticed that popular sites that offer web QR code scanning no longer seem to work, so I'm wondering if this library has become extinct.

**Comment by IstoraMandiri** [comment]
Hi,

Sorry but iOS does not support the getMediaStream api

http://caniuse.com/#feat=stream

Try on android?

**Comment by drone1** [comment]
It might be worth mentioning this on the github page if you don't already
(I didn't notice it if you do).

**Comment by IstoraMandiri** [comment]
I do, please see the first paragraph

**Comment by drone1** [comment]
Okie dokes. My bad. Thanks.
