### ISSUE TITLE
camera does not open on safari mobile

### ISSUE THREAD

**Issue by desmillicious** [hitchcott/meteor-qr-code-scanner#4]
The scanner works fine on safari, but not on mobile safari

When you load it on mobile safari a "play" button appears... see here: http://howmuchcoin.com
## EDIT

No dice, [getUserMedia stream](http://caniuse.com/#feat=stream) is not supported in those browsers. Are there any decent alternative APIs?

**Comment by desmillicious** [comment]
Seems from ios6 you can use:

`<input type="file" accept="video/*" capture="camera">` as per [stackoverflow answer](http://stackoverflow.com/a/14295860)

I may trial this

**Comment by IstoraMandiri** [comment]
Sorry, iOS does not support the `getUserMedia` api, so isn't supported.

Write to Apple and ask them to implement it!
